import 'package:dekornata_submission_test/models/product.dart';

Map<ImageTitle, String> productImageFile = {
  ImageTitle.RectangularTissueBox: "assets/images/rectangular-tissue-box.jpeg",
  ImageTitle.AiraTray: "assets/images/aira-tray.jpeg",
  ImageTitle.CacaCoaster: "assets/images/caca-coaster.jpeg",
  ImageTitle.CielServingBoard: "assets/images/ciel-serving-board.jpeg",
  ImageTitle.ClemencePlate: "assets/images/clemence-plate.jpeg",
  ImageTitle.CookiePlate: "assets/images/cookie-plate.jpeg",
  ImageTitle.HexagonCoaster: "assets/images/hexagon-coaster.jpeg",
  ImageTitle.MahoganyTray: "assets/images/mahogany-tray.jpeg",
  ImageTitle.SquareTissueBox: "assets/images/square-tissue-box.jpeg",
  ImageTitle.SquareTray: "assets/images/square-tray.jpeg",
  ImageTitle.StorageBox: "assets/images/storage-box.jpeg",
  ImageTitle.WoodenCoaster: "assets/images/wooden-coaster.jpeg",
  ImageTitle.WoodCraft: "assets/images/wood-craft.png",
  ImageTitle.TariTissueBox: "assets/images/tari-tissue-box.jpeg",
  ImageTitle.PlacematePlacemat: "assets/images/placemate-placemat.jpeg",
  ImageTitle.EcengPlacematCoaster: "assets/images/eceng-placemat-coaster.jpeg",
  ImageTitle.AkilaBambooBasketTray:
      "assets/images/akila-bamboo-basket-tray.jpeg",
  ImageTitle.RadiBamboo: "assets/images/radi-bamboo.jpeg",
  ImageTitle.LakaBambooTray: "assets/images/laka-bamboo-tray.jpeg",
  ImageTitle.RectaEcengBasketTray: "assets/images/recta-eceng-basket-tray.jpeg",
  ImageTitle.CaniMiniBasket: "assets/images/cani-mini-basket.jpeg",
  ImageTitle.SilaBasketSet: "assets/images/sila-basket-set.jpeg",
  ImageTitle.KibuBambooBasket: "assets/images/kibu-bamboo-basket.jpeg",
  ImageTitle.TinsaBambooBasketTray:
      "assets/images/tinsa-bamboo-basket-tray.jpeg",
  ImageTitle.NaruBambooTray: "assets/images/naru-bamboo-tray.jpeg",
  ImageTitle.WeaveCraft: "assets/images/weave-craft.png",
  ImageTitle.AlirPlate: "assets/images/alir-plate.jpeg",
  ImageTitle.RupaPlate: "assets/images/rupa-plate.jpeg",
  ImageTitle.KilauCup: "assets/images/kilau-cup.jpeg",
  ImageTitle.PekatCup: "assets/images/pekat-cup.jpeg",
  ImageTitle.PijarJug: "assets/images/pijar-jug.jpeg",
  ImageTitle.SemarTeapot: "assets/images/semar-teapot.jpeg",
  ImageTitle.GeloraPitcher: "assets/images/gelora-pitcher.jpeg",
  ImageTitle.SeduhTeapot: "assets/images/seduh-teapot.jpeg",
  ImageTitle.KalaCup: "assets/images/kala-cup.jpeg",
  ImageTitle.EratSaltnPepperStacker:
      "assets/images/erat-salt-n-pepper-stacker.jpeg",
  ImageTitle.KibasTeacup: "assets/images/kibas-teacup.jpeg",
  ImageTitle.LesungCupSet: "assets/images/lesung-cup.jpeg",
  ImageTitle.Ceramics: "assets/images/ceramics.png",
};

Map<String, ImageTitle> availableProductsToImage = {
  "Aira Tray": ImageTitle.AiraTray,
  "Caca Coaster": ImageTitle.CacaCoaster,
  "Ciel Serving Board": ImageTitle.CielServingBoard,
  "Clemence Plate": ImageTitle.ClemencePlate,
  "Cookie Plate": ImageTitle.CookiePlate,
  "Hexagon Coaster": ImageTitle.HexagonCoaster,
  "Mahogany Tray": ImageTitle.MahoganyTray,
  "Rectangular Tissue Box": ImageTitle.RectangularTissueBox,
  "Square Tissue Box": ImageTitle.SquareTissueBox,
  "Square Tray": ImageTitle.SquareTray,
  "Storage Box": ImageTitle.StorageBox,
  "Wooden Coaster": ImageTitle.WoodenCoaster,
  "Tari Tissue Box": ImageTitle.TariTissueBox,
  "Placemate Placemat": ImageTitle.PlacematePlacemat,
  "Eceng Placemat & Coaster": ImageTitle.EcengPlacematCoaster,
  "Akila Bamboo Basket Tray": ImageTitle.AkilaBambooBasketTray,
  "Radi Bamboo": ImageTitle.RadiBamboo,
  "Laka Bamboo Tray": ImageTitle.LakaBambooTray,
  "Recta Eceng Basket Tray": ImageTitle.RectaEcengBasketTray,
  "Cani Mini Basket": ImageTitle.CaniMiniBasket,
  "Sila Basket Set of 2": ImageTitle.SilaBasketSet,
  "Kibu Bamboo Basket": ImageTitle.KibuBambooBasket,
  "Tinsa Bamboo Basket Tray": ImageTitle.TinsaBambooBasketTray,
  "Naru Bamboo Tray": ImageTitle.NaruBambooTray,
  "Alir Plate": ImageTitle.AlirPlate,
  "Rupa Plate": ImageTitle.RupaPlate,
  "Kilau Cup": ImageTitle.KilauCup,
  "Pekat Cup": ImageTitle.PekatCup,
  "Pijar Cup": ImageTitle.PijarJug,
  "Semar Teapot": ImageTitle.SemarTeapot,
  "Gelora Pitcher": ImageTitle.GeloraPitcher,
  "Seduh Teapot": ImageTitle.SeduhTeapot,
  "Kala Cup": ImageTitle.KalaCup,
  "Erat Salt & Pepper Stacker": ImageTitle.EratSaltnPepperStacker,
  "Kibas Teacup": ImageTitle.KibasTeacup,
  "Lesung Cup Set": ImageTitle.LesungCupSet,
};

Map<String,double> availableProductToPrice = {
  "Aira Tray": 128000,
  "Caca Coaster": 20000,
  "Ciel Serving Board": 70000,
  "Clemence Plate": 72000,
  "Cookie Plate": 65000,
  "Hexagon Coaster": 12000,
  "Mahogany Tray": 115000,
  "Rectangular Tissue Box": 85000,
  "Square Tissue Box": 95000,
  "Square Tray": 98000,
  "Storage Box": 128000,
  "Wooden Coaster": 6000,
  "Tari Tissue Box": 25000,
  "Placemate Placemat": 45000,
  "Eceng Placemat & Coaster": 20000,
  "Akila Bamboo Basket Tray": 490000,
  "Radi Bamboo": 680000,
  "Laka Bamboo Tray": 525000,
  "Recta Eceng Basket Tray": 135000,
  "Cani Mini Basket": 50000,
  "Sila Basket Set of 2": 115000,
  "Kibu Bamboo Basket": 490000,
  "Tinsa Bamboo Basket Tray": 580000,
  "Naru Bamboo Tray": 490000,
  "Alir Plate": 190000,
  "Rupa Plate": 205000,
  "Kilau Cup": 175000,
  "Pekat Cup": 120000,
  "Pijar Cup": 190000,
  "Semar Teapot": 330000,
  "Gelora Pitcher": 220000,
  "Seduh Teapot": 300000,
  "Kala Cup": 90000,
  "Erat Salt & Pepper Stacker": 160000,
  "Kibas Teacup": 75000,
  "Lesung Cup Set": 195000,
};

Map<String, ImageTitle> categoriesToImageMap = {
  "Wood Craft": ImageTitle.WoodCraft,
  "Weave Craft": ImageTitle.WeaveCraft,
  "Ceramics": ImageTitle.Ceramics,
};

Map<ProductCategory, List<String>> categorizeProduct = {
  ProductCategory.WoodCraft: [
    "Aira Tray",
    "Caca Coaster",
    "Ciel Serving Board",
    "Clemence Plate",
    "Cookie Plate",
    "Hexagon Coaster",
    "Mahogany Tray",
    "Rectangular Tissue Box",
    "Square Tissue Box",
    "Square Tray",
    "Storage Box",
    "Wooden Coaster",
  ],
  ProductCategory.WeaveCraft: [
    "Tari Tissue Box",
    "Placemate Placemat",
    "Eceng Placemat & Coaster",
    "Akila Bamboo Basket Tray",
    "Radi Bamboo",
    "Laka Bamboo Tray",
    "Recta Eceng Basket Tray",
    "Cani Mini Basket",
    "Sila Basket Set of 2",
    "Kibu Bamboo Basket",
    "Tinsa Bamboo Basket Tray",
    "Naru Bamboo Tray",
  ],
  ProductCategory.Ceramics: [
    "Alir Plate",
    "Rupa Plate",
    "Kilau Cup",
    "Pekat Cup",
    "Pijar Cup",
    "Semar Teapot",
    "Gelora Pitcher",
    "Seduh Teapot",
    "Kala Cup",
    "Erat Salt & Pepper Stacker",
    "Kibas Teacup",
    "Lesung Cup Set",
  ]
};
